### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by andreimarcu** [andreimarcu/aambucket#1]
- [ ] command to join/part channels (when kicked, etc)
- [ ] implement deleting all facts from a factoid
- [ ] implement X =~ /thing/
- [ ] implement literals
- [ ] implement variables such as $someone, etc
